% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Apr-2021 09:39:27
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('trainingkelulusanmhs.mat');

class = 3;

classification = saveVarsMat.classification; % <1x1 ClassificationKNN> unsupported class

group = [4; 2; 4; 3; 2; 3; 1; 2; 1; 3; 4];

sampel = [3.15 3.5 5];

training = ...
  [3.81 3.5 5;
   3 7 1;
   3.67 4.1 3;
   3.32 3.8 5;
   3 5 2;
   3.2 4 4;
   2.75 6 3;
   3 5 5;
   2.52 7 0;
   3.47 4.6 3;
   3.9 4.2 2];

clear saveVarsMat;
